apiVersion: v1
kind: Service
metadata:
  name: react-k8s
spec:
  type: NodePort
  selector:
    app: react-k8s
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: react-k8s